version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db-taches
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=taches_db
    ports:
      - '5433:5433'

  projets:
    container_name: taches_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8070:8070'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/taches_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
