eureka:
  client:
    service-url:
      dedefaultZone: http://localhost:8761/eureka
    register-with-eureka: true

server:
  port: 8084
spring:
  application:
    name: security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/utilisateurs
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: db/megration
    baseline-on-migrate: true
