version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db-discovery
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=discovery_db
    ports:
      - '5434:5434'

  projets:
    container_name: discovery_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8761:8761'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/discovery_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
