version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=projets_db
    ports:
      - '5432:5432'

  projets:
    container_name: projets_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/projets_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
