eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defautltZone: http://localhost:8761/eureka
server:
  port: 8070
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: taches
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tache
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: db/megration
    baseline-on-migrate: true

application:
  config:
    ressources-url: http://localhost:8222/api/ressources/
