version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db-security
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=security_db
    ports:
      - '5434:5434'

  projets:
    container_name: security_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8084:8084'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/security_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
